# Generated by Django 4.0.3 on 2022-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_status_product_tag_product_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images4',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
