# Generated by Django 4.0.3 on 2022-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_categoryoffer_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
