# Generated by Django 4.0.3 on 2022-05-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z ]*$', 'Enter a valid name'), django.core.validators.MinLengthValidator(3, 'the field must contain atleat 3 character')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z ]*$', 'Enter a valid name'), django.core.validators.MinLengthValidator(3, 'the field must contain atleat 3 character')]),
        ),
    ]
