# Generated by Django 4.0.3 on 2022-05-29 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z ]*$', 'Enter a valid name'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z ]*$', 'Enter a valid name'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid phone number')]),
        ),
    ]
