# Generated by Django 4.0.3 on 2022-05-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_status_category_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
