# Generated by Django 4.0.3 on 2022-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discout',
            new_name='discount',
        ),
    ]
