# Generated by Django 4.0.3 on 2022-05-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_couponuseduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuseduser',
            name='count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
